#!/bin/bash

prog_name='Android Power Monitor'

bat_level_old=-1;
first=1

sleep 1

while true
do
	conn_status=`adb get-state`

	if [ ! $conn_status = 'device' ]
	then
        if [ ! "$first" ]
        then
		    notify-send -i error "$prog_name" 'Device disconnected'
		    first=1
            bat_level_old=-1
        else
            sleep 1
            continue
        fi
	fi

	bat_level=`adb shell "cat /sys/class/power_supply/battery/capacity" | tr -d '\r\n'`

	if [ "$first" -eq 1 ]
	then
		bat_level_avg=0
		let "bat_level_index = $bat_level / 20 * 20"
		first=0
	else
		let "bat_level_avg = $bat_level % 20"
		bat_level_index=$bat_level
	fi

	if [ "$bat_level" -gt "$bat_level_old" ] && [ "$bat_level_avg" -eq 0 ]
	then
        if [ "$bat_level_avg" -lt 100 ]
        then
	        icon_name="battery-0$bat_level_index-charging"
        else
	        icon_name="battery-$bat_level_index-charging"
        fi
		notify-send -i "$icon_name" "$prog_name" "Battery level: $bat_level%"
	fi

	if [ $bat_level == 100 ]
	then
		exit 0
	fi

	sleep 1

    bat_level_old=$bat_level
done
